# Generated by Django 5.2.13 on 2026-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mensaje_pago',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('mock_card', 'Tarjeta (mock)'), ('mock_transfer', 'Transferencia (mock)'), ('cash_on_delivery', 'Pago contra entrega')], default='mock_card', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
