# Generated by Django 5.2.13 on 2026-04-19 22:24

from django.db import migrations
from django.utils.text import slugify


CATEGORY_NAMES = [
    "whisky",
    "ron",
    "vodka",
    "vino",
    "champagne",
    "gin",
    "tequila",
    "licores",
    "espumantes",
    "otros",
]


def infer_category_slug(product):
    source = f"{product.nombre} {product.descripcion}".lower()
    lookup = (
        ("whisky", ("whisky", "whiskey", "bourbon", "scotch")),
        ("ron", ("ron", "rum")),
        ("vodka", ("vodka",)),
        ("vino", ("vino", "wine", "cabernet", "merlot", "sauvignon", "carmenere")),
        ("champagne", ("champagne", "champan")),
        ("gin", ("gin",)),
        ("tequila", ("tequila",)),
        ("licores", ("licor", "liqueur", "amaretto", "baileys")),
        ("espumantes", ("espumante", "prosecco", "cava")),
    )
    for slug, keywords in lookup:
        if any(keyword in source for keyword in keywords):
            return slug
    return "otros"


def seed_and_backfill(apps, schema_editor):
    CategoriaProducto = apps.get_model("MainApp", "CategoriaProducto")
    Producto = apps.get_model("MainApp", "Producto")
    Pedido = apps.get_model("MainApp", "Pedido")

    categories_by_slug = {}
    for category_name in CATEGORY_NAMES:
        category, _ = CategoriaProducto.objects.get_or_create(
            slug=slugify(category_name),
            defaults={"nombre": category_name.title()},
        )
        categories_by_slug[category.slug] = category

    for product in Producto.objects.filter(categoria__isnull=True):
        category_slug = infer_category_slug(product)
        product.categoria = categories_by_slug[category_slug]
        product.save(update_fields=["categoria"])

    Pedido.objects.filter(estado_pedido="pendiente").update(estado_pedido="recibido")
    Pedido.objects.filter(estado_pedido="enviado").update(estado_pedido="en_camino")


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0004_categoriaproducto_alter_pedido_estado_pedido_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
    ]
